name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}" > .env.local

      - name: Build
        run: npm run build

      - name: Add .nojekyll file
        run: |
          touch out/.nojekyll
          cp index.html out/

      - name: Fix paths in HTML files
        run: |
          find out -name "*.html" -type f -exec sed -i 's/"\/_next/".\/chat-robot\/_next/g' {} \;
          find out -name "*.html" -type f -exec sed -i 's/"\/_next/"..\/_next/g' {} \;

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
